apiVersion: v1
kind: Service
metadata:
  name: ai-model-explorer
  labels:
    app: ai-model-explorer

spec:
  type: NodePort

  selector:
    app: ai-model-explorer

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000